/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../public/world.glb 
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function Model(...props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/world.glb");
  return (
    <group {...props} dispose={null}>
      {/* <pointLight
        intensity={434811.305}
        decay={2}
        color='#bdffd1'
        position={[-16.215, 14.715, -10.515]}
        rotation={[-1.839, 0.602, 1.932]}
        scale={1722.857}
      /> */}
      <PerspectiveCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        fov={15.895}
        position={[70.053, 13.91, -0.79]}
        rotation={[-1.922, -1.077, -1.966]}
        scale={1.038}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[-2.211, -0.281, 3.265]}
        rotation={[0.014, 0.014, -0.012]}
        scale={[14.934, 0.642, 15.446]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.004"]}
        position={[4.253, 3.904, 1.006]}
        scale={[1.89, 3.642, 1.89]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.003"]}
        position={[-3.246, 3.422, 1.716]}
        rotation={[-0.042, -1.098, 3.111]}
        scale={[-1.612, -3.073, -2.315]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0.661, 4.494, 1.29]}
        rotation={[0.175, -0.131, -0.035]}
        scale={[1.936, 1.449, 0.31]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[0.925, 5, 1.172]}
        scale={[2.408, 1.457, 0.31]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["Material.005"]}
        position={[5.581, 6.953, -0.898]}
        rotation={[1.647, 0.001, 3.14]}
        scale={[0.184, 1.453, 0.207]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.001"]}
        position={[7.007, 0.028, 10.418]}
        rotation={[-3.13, 0, -Math.PI]}
        scale={[-4.663, -0.175, -7.736]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.002"]}
        position={[6.362, 0.111, -7.38]}
        rotation={[-0.351, -1.519, -0.37]}
        scale={[2.566, 0.389, 4.343]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-16.363, 1.56, -6.28]}
        rotation={[0.012, -0.025, -0.085]}
        scale={[0.23, 1.042, 4.607]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-16.619, 1.53, 0.53]}
        rotation={[-1.784, -1.451, -1.79]}
        scale={[2.222, 1.042, 0.087]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-16.318, 1.439, 3.217]}
        rotation={[-0.008, -0.623, -0.03]}
        scale={[0.555, 1.142, 0.165]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[-16.415, 2.96, 0.304]}
        rotation={[-1.633, 1.445, 0.074]}
        scale={[0.366, 1.797, 0.085]}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials["Material.005"]}
        position={[-3.645, 5.934, -0.131]}
        rotation={[1.547, -0.024, 2.626]}
        scale={[0.244, 0.185, 0.269]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[2.596, 1.406, -9.057]}
        scale={[0.128, 1.121, 0.136]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[3.069, 1.414, -5.014]}
        scale={[0.128, 1.029, 0.136]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[9.171, -0.633, -4.964]}
        scale={[0.128, 0.887, 0.136]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[8.517, -0.881, -9.805]}
        scale={[0.128, 0.435, 0.136]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[-16.521, 1.326, 11.696]}
        rotation={[0.02, -0.017, -0.013]}
        scale={[0.366, 1.143, 6.9]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials["Material.003"]}
        position={[-1.937, 2.22, -0.17]}
        rotation={[0.014, -0.14, -0.021]}
        scale={[1.518, 4.238, 1.552]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[-10.734, 0.939, -6.957]}
        rotation={[0.034, -0.006, -0.031]}
        scale={[3.539, 0.257, 2.769]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[10.156, 1.093, -9.14]}
        scale={[0.128, 0.8, 0.136]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[10.229, 1.084, -5.252]}
        scale={[0.128, 0.782, 0.136]}
      />
      <mesh
        geometry={nodes.Grid.geometry}
        material={materials["Material.003"]}
        position={[6.489, 2.155, -7.334]}
        rotation={[0, -0.018, -0.082]}
        scale={[4.651, 1.46, 2.92]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["Material.002"]}
        position={[-0.701, 0.004, 14.853]}
        rotation={[-0.5, -1.488, -0.496]}
        scale={[2.566, 0.389, 4.343]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-1.563, 1.277, -11.18]}
        rotation={[2.271, 1.551, 0.778]}
        scale={[0.238, 1, 15.06]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[12.066, 0.724, 3.878]}
        rotation={[-3.13, -0.001, -0.007]}
        scale={[0.261, 0.816, 15.286]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials.Material}
        position={[-2.801, 1.198, 18.56]}
        rotation={[2.137, 1.546, 1.001]}
        scale={[0.238, 1, 15.06]}
      />
    </group>
  );
}

useGLTF.preload("/world.glb");
