/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../public/donut.glb 
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function Model(...props) {
  const { nodes, materials } = useGLTF("/donut.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={true}
        far={100}
        near={0.1}
        fov={12.403}
        position={[-78.853, 52.088, 9.405]}
        rotation={[-0.627, 0.71, 0.441]}
        scale={12.724}
      />
      <mesh geometry={nodes.Donut.geometry} material={materials["Material.001"]} position={[12.359, 3.746, -4.182]} scale={26.795} />
      <mesh geometry={nodes.Icing.geometry} material={materials.Material} position={[12.359, 3.746, -4.182]} scale={26.795} />
      <mesh geometry={nodes.Plane.geometry} material={materials["Material.002"]} position={[0.334, 1.59, -6.525]} scale={32.724} />
    </group>
  );
}

useGLTF.preload("/donut.glb");
